### ISSUE TITLE
incompatibility

### ISSUE THREAD

**Issue by shyricaus** [TanguyOrtegat/esx_jb_stopvehicledespawn#3]
incompatible with esx_vehicleshoes and esx-qalle-sell vehicles, would have to see this for us would be very useful

**Comment by TanguyOrtegat** [comment]
it is true that vehicles bought from vehicleshop are not networked trough the script, but jut put them un garage and take them out and it is fixed. well quall idk how their garage works 🤷‍♂️

**Comment by shyricaus** [comment]
I mean the sale

**Comment by shyricaus** [comment]
after selling the vehicle keeps appearing

**Comment by shyricaus** [comment]
another script that will give problem at the time of selling is esx_ownedcarthief

**Comment by shyricaus** [comment]
I wanted to know how to add your command in these scripts because I tried more without success

networkid = NetworkGetNetworkIdFromEntity(vehicle)
TriggerServerEvent('vehicleenteredingarage', networkid)

**Comment by TanguyOrtegat** [comment]
first you need to network the vehicles
then get their id :) then when you steal them remove the id from the script.

something like that

**Comment by shyricaus** [comment]
these are there and when are you going to sell the vehicle in the specific place

**Comment by shyricaus** [comment]
type for sale of vehcleshop

**Comment by shyricaus** [comment]
I wanted the vehicle to sell the vehicle in the vehicle shop, the vehicle sake of vehicles.json

**Comment by shyricaus** [comment]
I took longer to get it to work with all my vehicle sales scripts
